[package]
name = "seredies"
version = "0.1.0"
authors = ["Nathan West <Lucretiel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
memchr = "2.5.0"
serde = { version = "1.0.118", default-features = false, features = ["derive"] }
thiserror = "1.0.32"

[dev-dependencies]
cool_asserts = "2.0.3"
serde_test = "1.0.143"
